### ISSUE TITLE
IR Not Working

### ISSUE THREAD

**Issue by coxtor** [yoziru/esphome-argoclima-ir#5]
Hi, cool project! 
I am using a m5stack atom s3 lite and the compilation/upload works fine. However the IR diode does not appear to do anything (at least when testing with a camera). All other exposed things like led or button work fine. 
Any idea what could be wrong? There are no errors in the logs.

**Comment by yoziru** [comment]
should be fixed in https://github.com/yoziru/esphome-argoclima-ir/commit/b4dc4a20bbb6847ccad9b6b6f8da5420b8869e2a (wasn't using the right pin before)
